# Generated by Django 4.2.7 on 2023-12-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='custom_learning_styles',
            field=models.ManyToManyField(blank=True, to='learning.customlearningstyle'),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_styles',
            field=models.ManyToManyField(blank=True, to='learning.learningstyle'),
        ),
    ]
