# Generated by Django 4.2.7 on 2023-12-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_material_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='content_link',
        ),
        migrations.RemoveField(
            model_name='material',
            name='content_text',
        ),
        migrations.RemoveField(
            model_name='material',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='material',
            name='course',
        ),
        migrations.RemoveField(
            model_name='material',
            name='custom_learning_style',
        ),
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/'),
        ),
    ]
