# Generated by Django 4.2.7 on 2023-12-06 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_remove_material_content_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='learning.unit'),
        ),
    ]
