# Generated by Django 4.2.7 on 2023-12-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_material_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
