# Generated by Django 4.2.7 on 2023-12-26 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_unit_sequence_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='sequence_number',
        ),
    ]
