# Generated by Django 4.2.7 on 2024-01-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_alter_quiz_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['sequence_number']},
        ),
        migrations.AddField(
            model_name='unit',
            name='sequence_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
