# Generated by Django 4.2.7 on 2024-01-03 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_quizquestion_quizanswer_studentresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningstyleassessment',
            name='assessment_dates',
        ),
        migrations.RemoveField(
            model_name='learningstyleassessment',
            name='current_learning_style',
        ),
        migrations.RemoveField(
            model_name='learningstyleassessment',
            name='initial_learning_style',
        ),
        migrations.AddField(
            model_name='learningstyleassessment',
            name='assessment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='learningstyleassessment',
            name='learning_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.learningstyle'),
        ),
    ]
