# Generated by Django 4.2.7 on 2024-01-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0014_quizresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
