# Generated by Django 4.2.7 on 2024-01-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0016_unitgrade_coursegrade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unitgrade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='unitgrade',
            name='attempt',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
