# Generated by Django 4.2.7 on 2024-01-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0017_alter_unitgrade_unique_together_unitgrade_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.IntegerField(default=60),
        ),
    ]
