# Generated by Django 4.2.7 on 2024-01-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0018_quiz_passing_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='num_answers_to_display',
            field=models.PositiveIntegerField(default=4, help_text='Number of answers to display per question.'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='num_questions_to_display',
            field=models.PositiveIntegerField(default=5, help_text='Number of questions to display to the student.'),
        ),
    ]
