# Generated by Django 4.2.7 on 2024-01-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0019_quiz_num_answers_to_display_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='num_answers_to_display',
            field=models.PositiveIntegerField(default=4, help_text='Numero de respuestas a mostrar por pregunta.'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='num_questions_to_display',
            field=models.PositiveIntegerField(default=5, help_text='Numero de preguntas a mostrar al alumno.'),
        ),
    ]
